language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - windows
  - osx
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
notifications:
  email:
    on_success: never
branches:
  only:
    - master
