name: onefetch
base: core18 # the base snap is the execution environment for this snap
adopt-info: onefetch
summary: Git repository summary on your terminal
description: |
  Onefetch is a command-line system information tool that displays information
  about your Source Code directly on your terminal..

grade: stable
confinement: strict

parts:
  onefetch:
    plugin: rust
    source: .
    stage-packages:
      - git
    override-build: |
      snapcraftctl build 
      snapcraftctl set-version $(git describe --abbrev=0 --tags)

apps:
  onefetch:
    command: bin/onefetch
    plugs: 
      - home
      - removable-media
